northstar:
  message.endpoint: http://localhost:51888
  server.endpoint: http://localhost:8888
  
spring:
    data:
        mongodb:
            host: 127.0.0.1
            port: 27017
            database: DB_BAR_DATA
logging:
  level: 
    root: info
  path: log/NorthstarStrategyClient/
  
  
strategy-setting:
  demo-strategy:
    gatewayId: simnow724
    accountId: 094020@simnow724
    strategyName: DemoStrategy
    mdContracts: rb2010,AP010,m2009,IF2006,SC2006
    tdContracts: rb2010
  shadow-strategy:
    gatewayId: simnow724
    accountId: CTP-SimNow
    strategyName: ShadowStrategy
    mdContracts: rb2005,AP005,cu2005,IF2006,au2006
    tdContracts: rb2005
    followAccount: CTP-SimNow
    
    